# Generated by Django 3.0.4 on 2020-04-02 16:13

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=5, null=True)),
                ('post', models.CharField(max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'api_user',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=50)),
                ('updateBy', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(max_length=50)),
                ('updateAt', models.DateTimeField(max_length=50)),
                ('isActive', models.BooleanField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'api_agency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=50)),
                ('updateBy', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(max_length=50)),
                ('updateAt', models.DateTimeField(max_length=50)),
                ('isActive', models.BooleanField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('sigle', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'api_bank',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=50)),
                ('updateBy', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(max_length=50)),
                ('updateAt', models.DateTimeField(max_length=50)),
                ('isActive', models.BooleanField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('tutel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutelId', to='api.Category')),
            ],
            options={
                'verbose_name': 'api_category',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=50)),
                ('updateBy', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(max_length=50)),
                ('updateAt', models.DateTimeField(max_length=50)),
                ('isActive', models.BooleanField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'api_locality',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=50)),
                ('updateBy', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(max_length=50)),
                ('updateAt', models.DateTimeField(max_length=50)),
                ('isActive', models.BooleanField(max_length=50)),
                ('agencyId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Agency')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'api_user_agency',
                'ordering': ['agencyId'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=50)),
                ('updateBy', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(max_length=50)),
                ('updateAt', models.DateTimeField(max_length=50)),
                ('isActive', models.BooleanField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('role', models.TextField(max_length=1000)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
            options={
                'verbose_name': 'api_indicator',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IndAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=50)),
                ('updateBy', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(max_length=50)),
                ('updateAt', models.DateTimeField(max_length=50)),
                ('isActive', models.BooleanField(max_length=50)),
                ('data', models.IntegerField()),
                ('type_value', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('agencyId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Agency')),
                ('indicatorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Indicator')),
            ],
            options={
                'verbose_name': 'api_ind_agency',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CategoryValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=50)),
                ('updateBy', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(max_length=50)),
                ('updateAt', models.DateTimeField(max_length=50)),
                ('isActive', models.BooleanField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
            options={
                'verbose_name': 'api_category_value',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='bankId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Bank'),
        ),
        migrations.AddField(
            model_name='agency',
            name='localityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Locality'),
        ),
    ]
