# Generated by Django 3.0.4 on 2020-03-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicagency',
            old_name='value',
            new_name='data',
        ),
        migrations.AddField(
            model_name='category',
            name='tutel',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutelId', to='api.Category'),
            preserve_default=False,
        ),
    ]
