# Generated by Django 3.0.5 on 2020-04-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='indicators',
            field=models.ManyToManyField(through='api.IndAgency', to='api.Indicator'),
        ),
        migrations.AlterField(
            model_name='indagency',
            name='agencyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='indagency',
            name='indicatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Indicator'),
        ),
    ]
