# Generated by Django 3.0.5 on 2020-04-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200411_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='bankId',
            new_name='bank',
        ),
    ]
