# Generated by Django 3.0.5 on 2020-04-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200412_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='localityId',
            new_name='locality',
        ),
    ]
