# Generated by Django 3.0.5 on 2020-04-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200412_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useragency',
            old_name='userId',
            new_name='user',
        ),
    ]
