# Generated by Django 3.0.5 on 2020-04-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200412_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragency',
            options={'ordering': ['agency'], 'verbose_name': 'api_user_agency'},
        ),
        migrations.RenameField(
            model_name='useragency',
            old_name='agencyId',
            new_name='agency',
        ),
    ]
