# Generated by Django 3.0.5 on 2020-04-12 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200412_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='indicator',
            name='type_value',
            field=models.CharField(default='int', max_length=50),
        ),
    ]
