# Generated by Django 3.0.5 on 2020-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200412_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='data',
            field=models.IntegerField(default=0),
        ),
    ]
