# Generated by Django 3.0.5 on 2020-04-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragency',
            options={'ordering': ['agencyId'], 'verbose_name': 'api_user_agency'},
        ),
        migrations.RenameField(
            model_name='useragency',
            old_name='agency',
            new_name='agencyId',
        ),
        migrations.RenameField(
            model_name='useragency',
            old_name='user',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='agency',
        ),
    ]
