# Generated by Django 3.0.5 on 2020-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200413_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ManyToManyField(through='api.UserAgency', to='api.Agency'),
        ),
    ]
