# Generated by Django 3.0.5 on 2020-04-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.TextField(default='-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='role',
            field=models.TextField(default='-', max_length=1000),
        ),
    ]
