# Generated by Django 3.0.5 on 2020-04-14 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200414_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['id'], 'verbose_name': 'api_agency'},
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='date',
            new_name='datee',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='data',
            new_name='value',
        ),
    ]
