# Generated by Django 3.0.5 on 2020-04-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200414_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='categoryId',
            new_name='category',
        ),
    ]
