# Generated by Django 3.0.5 on 2020-04-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200414_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='datee',
            field=models.CharField(default='01/01/2000', max_length=50),
        ),
    ]
