# Generated by Django 3.0.5 on 2020-04-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200414_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='datee',
            new_name='date',
        ),
    ]
