# Generated by Django 3.0.4 on 2020-04-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200417_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tutel',
        ),
        migrations.RemoveField(
            model_name='categoryvalue',
            name='categoryId',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Category'),
        ),
        migrations.AddField(
            model_name='categoryvalue',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoriesvalue', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agency', to='api.Bank'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='indicators',
            field=models.ManyToManyField(related_name='agency', through='api.IndAgency', to='api.Indicator'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agency', to='api.Locality'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='indicators', to='api.Category'),
        ),
    ]
