# Generated by Django 3.0.4 on 2020-04-22 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200422_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indagency',
            name='agencyId',
        ),
        migrations.RemoveField(
            model_name='indagency',
            name='indicatorId',
        ),
        migrations.AddField(
            model_name='indagency',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicagency', to='api.Agency'),
        ),
        migrations.AddField(
            model_name='indagency',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicagency', to='api.Indicator'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agency', to='api.Bank'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='indicators',
            field=models.ManyToManyField(null=True, related_name='agency', through='api.IndAgency', to='api.Indicator'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agency', to='api.Locality'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='indicators', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.ManyToManyField(related_name='user', through='api.UserAgency', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='useragency',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='useragency', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='useragency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='useragency', to=settings.AUTH_USER_MODEL),
        ),
    ]
