# Generated by Django 3.0.4 on 2020-04-23 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200422_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indagency',
            options={'ordering': ['date_operation'], 'verbose_name': 'api_ind_agency'},
        ),
        migrations.RemoveField(
            model_name='indagency',
            name='date',
        ),
        migrations.AddField(
            model_name='indagency',
            name='date_operation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='agency',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='api.Bank'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='indicators',
            field=models.ManyToManyField(related_name='agency', through='api.IndAgency', to='api.Indicator'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='api.Locality'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='useragency',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useragency', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='useragency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useragency', to=settings.AUTH_USER_MODEL),
        ),
    ]
